config/routes.rb
Quinara::Application.routes.draw do
  resources :grades
  resources :courses do
    member do
      get :formato_evaluaciones
    end
    resources :alumnos do
      member do
        post :toggle
      end
    end
    resources :evaluacions, path: "evaluaciones" do
      member do
        get :view
        get :calificar
        get :delete_my_answer
        post :calificar_respuestas
        post :remove_file
        patch :validate
      end
      collection do
        get :reuse
        post :reuse_evaluacion
        post :validate
      end
      resources :respuestas
    end
  end
  resources :answer_evaluacion do
    member do
      get :view
    end
  end
  resources :me

  get "login", to: "sessions#index", as: :login
  get "logout", to: "sessions#destroy", as: :logout
  resources :sessions

  get :admin, to: "admin#index"
  namespace :admin do
    resources :users
    resources :courses do
      resources :evaluaciones_formato
    end
  end
  resources :password_resets
  root "home#index"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  username            :string(255)      not null
#  email               :string(255)
#  crypted_password    :string(255)
#  salt                :string(255)
#  nombres             :string(255)
#  apellidos           :string(255)
#  fecha_nacimiento    :date
#  identificacion      :string(255)
#  tipo_identificacion :string(255)
#  direccion           :string(255)
#  telefono            :string(255)
#  admin               :boolean          default(FALSE)
#  created_at          :datetime
#  updated_at          :datetime
#  imagen              :string(255)
#

class User < ActiveRecord::Base
  authenticates_with_sorcery!
  include UserCourses
  include UserIdValidator
  include UserAdvises
  include UserEvaluaciones

# scopes:
  default_scope { order(:apellido_paterno, :nombres, :username) }

# attrs:
  attr_accessor :password_confirmation

# uploaders:
  mount_uploader :imagen, UserImagenUploader

# validations:
  validates :username, presence: true, :uniqueness =>  { :case_sensitive => false }
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, if: "password.present?"
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create
  validate :password_confirmation_matches
  validates :identificacion, :uniqueness => { :allow_blank => true }
  validates :nombres, :apellido_paterno, presence: true

# relationships:
  has_many :user_rols
  has_many :rols, through: :user_rols
  has_many :courses, through: :user_rols
  has_many :all_evaluaciones, through: :courses, source: :evaluaciones
  has_many :user_answers

# methods:
  def password_confirmation_matches
    errors.add(:password, "Confirmación no coincide") unless password == password_confirmation
  end
  def nombres_completos
    "#{nombres} #{apellido_paterno}"
  end
  def info_for_select
    "#{nombres_completos} (#{username})"
  end
  def nombres_o_username
    nombres.blank? ? username : nombres
  end

# class methods
  def self.users_for_select
    select(:id, :nombres, :apellido_paterno, :username).map {|u| [u.info_for_select, u.id] }
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController

    before_action :find_user, only: [:edit, :update, :destroy]

    def index
      @users = User.all
    end

    def new
      @user = User.new
      @show_all_fields = true
    end

    def edit
      @show_all_fields = true
    end

    def create
      @user = User.new user_params
      if @user.save
        flash["alert-success"] = "Usuario guardado"
        redirect_to action: :index
      else
        flash["alert-error"] = "Usuario no guardado"
        render :new
      end
    end

    def update
      if @user.update_attributes user_params
        flash["alert-success"] = "Usuario actualizado"
        redirect_to action: :index
      else
        flash["alert-error"] = "Usuario no actualizado"
        render :edit
      end
    end

    def destroy
      @user.destroy
      flash["alert-info"] = "Usuario eliminado"
      redirect_to action: :index
    end

    private

    def find_user
      @user = User.find params[:id]
    end

    def user_params
      params.require(:user).permit :username,
                                   :email,
                                   :imagen,
                                   :remove_imagen,
                                   :imagen_cache,
                                   :nombres,
                                   :apellido_paterno,
                                   :apellido_materno,
                                   :tipo_identificacion,
                                   :fecha_nacimiento,
                                   :identificacion,
                                   :direccion,
                                   :telefono,
                                   :password,
                                   :password_confirmation,
                                   :admin
    end

  end
end

app/views/admin/users/_form.html.erb
<%= title (@user.new_record? ? "Nuevo" : "Editar") + " usuario" %>

<%= form_for [:admin, @user] do |f| %>
  
  <%= render "form_fields", f: f %>

<% end %>

app/views/admin/users/_form_fields.html.erb
<%= form_errors_for f.object %>

<div class="field">
  <%= f.label :username, "Nombre de usuario:" %>
  <%= f.text_field :username, placeholder: "Utilizado para iniciar sesión", required: true %>
</div>

<div class="field">
  <%= f.label :email, "Email:" %>
  <%= f.email_field :email, placeholder: "E-mail", required: true %>
</div>

<% if @show_all_fields %>
  <div class="separator"></div>

  <div class="field">
    <%= f.label :admin, "Administrador:" %>
    <%= f.check_box :admin %>
  </div>
<% end %>

<div class="separator"></div>

<div class="field">
  <%= f.label :imagen, "Imagen:" %>
  <%= f.file_field :imagen %>
  <%= f.hidden_field :imagen_cache %>

  <div class="clearfix"></div>

  <div class="control-label inline_block">
    <%= image_tag f.object.imagen_url(:mini), :class => "profile_image mini" %>
  </div>
  <% if f.object.imagen? %>
    <%= f.check_box :remove_imagen %> Eliminar imagen
  <% end %>
</div>

<div class="field">
  <%= f.label :nombres, "Nombres:" %>
  <%= f.text_field :nombres, required: true %>
</div>

<div class="field">
  <%= f.label :apellido_paterno, "Apellido paterno:" %>
  <%= f.text_field :apellido_paterno, required: true %>
</div>

<div class="field">
  <%= f.label :apellido_materno, "Apellido materno:" %>
  <%= f.text_field :apellido_materno %>
</div>

<div class="field">
  <%= f.label :tipo_identificacion, "Tipo de identificación:" %>
  <%= f.select :tipo_identificacion, ["Cédula", "Pasaporte - Otro"] %>
</div>

<div class="field">
  <%= f.label :identificacion, "Identificación:" %>
  <%= f.text_field :identificacion %>
</div>

<div class="field">
  <%= f.label :direccion, "Dirección:" %>
  <%= f.text_field :direccion %>
</div>

<div class="field">
  <%= f.label :fecha_nacimiento, "Fecha de nacimiento:" %>
  <%= f.text_field :fecha_nacimiento, {:start_year => 1995, :class => "datepicker"} %>
</div>

<div class="field">
  <%= f.label :telefono, "Teléfono:" %>
  <%= f.telephone_field :telefono %>
</div>

<div class="separator"></div>

<div class="field">
  <%= f.label :password, "Contraseña:" %>
  <%= f.password_field :password, placeholder: "Contraseña para iniciar sesión" %>
</div>

<div class="field">
  <%= f.label :password_confirmation, "Confirmar contraseña:" %>
  <%= f.password_field :password_confirmation, placeholder: "Confirmar contraseña" %>
</div>
<div class="align_right">
  <span class="help-inline"><small>Dejar en blanco si no se desea cambiar la contraseña.</small></span>
</div>

<div class="actions">
  <% if f.object.new_record? %>
      <%= link_to "Cancelar", admin_users_path, :class => "atras_back" %>
  <% else %>
    <% if f.object == current_user %>
      <%= link_to "Cancelar", me_index_path, :class => "atras_back" %>
    <% else %>
      <%= link_to "Cancelar", admin_users_path, :class => "atras_back" %>
    <% end %>
  <% end %>
  <%= f.submit "Enviar", data: {:disable_with => 'Enviando..'} %>
</div>

app/views/admin/users/index.html.erb
<h1>Usuarios</h1>

<div class="actions">
    <%= link_to 'Nuevo', new_admin_user_path, :class => "crear_nuevo" %>
</div>

<table class="datos table table-hover">
  <thead>
    <tr>
      <th>Nombre de usuario</th>
      <th>Nombres</th>
      <th>Apellido paterno</th>
      <th>Apellido materno</th>
      <th>Identificación</th>
      <th>Dirección</th>
      <th>Teléfono</th>
      <th>Acciones</th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tr>
    <td>
      <%= user.username %>
      <div>
        <%= image_tag user.imagen_url(:tiny), :class => "profile_image tiny" %>
      </div>
      <% if user.admin %>
        <div>
          <span class="label label-info">Administrador</span>
        </div>
      <% end %>
    </td>
    <td><%= user.nombres %></td>
    <td><%= user.apellido_paterno %></td>
    <td><%= user.apellido_materno %></td>
    <td>
      <%= user.identificacion %>
      <% unless user.identificacion.blank? %>
        (<%= user.tipo_identificacion %>)
      <% end %>
    </td>
    <td><%= user.direccion %></td>
    <td><%= user.telefono %></td>
    <td class="align_center">
      <%= link_to "Calificaciones", grade_path(user), :class => "btn btn-mini" %>
      <%= link_to 'Editar', edit_admin_user_path(user), :class => 'editar_edit btn-mini' %>
      <%= link_to 'Eliminar', admin_user_path(user), method: :delete, data: { confirm: '¿Estás seguro de eliminar a '+user.nombres+' '+user.apellido_paterno+'?' }, :class => 'delete_destroy btn-mini' %>
    </td>
  </tr>
<% end %>
</table>