config/routes.rb
Quinara::Application.routes.draw do
  resources :grades
  resources :courses do
    member do
      get :formato_evaluaciones
    end
    resources :alumnos do
      member do
        post :toggle
      end
    end
    resources :evaluacions, path: "evaluaciones" do
      member do
        get :view
        get :calificar
        get :delete_my_answer
        post :calificar_respuestas
        post :remove_file
        patch :validate
      end
      collection do
        get :reuse
        post :reuse_evaluacion
        post :validate
      end
      resources :respuestas
    end
  end
  resources :answer_evaluacion do
    member do
      get :view
    end
  end
  resources :me

  get "login", to: "sessions#index", as: :login
  get "logout", to: "sessions#destroy", as: :logout
  resources :sessions

  get :admin, to: "admin#index"
  namespace :admin do
    resources :users
    resources :courses do
      resources :evaluaciones_formato
    end
  end
  resources :password_resets
  root "home#index"
end

app/controllers/admin/evaluaciones_formato_controller.rb
module Admin
  class EvaluacionesFormatoController < AdminController

    before_action :find_course

    def index
    end

    def new
    end

    def edit
      @formato = @course.evaluacion_formato
      render :new
    end

    def create
      if @course.evaluacion_formato
        @course.evaluacion_formato.destroy
      end
      formato = EvaluacionFormato.new course: @course
      formato.formatos_count = params[:formatos_count]
      formato.formato = {terms: params[:terms].permit!}
      formato.save!
      flash["alert-success"] = "Guardado."
      redirect_to action: :index
    end

    def destroy
      @course.evaluacion_formato.destroy
      flash["alert-success"] = "Eliminado."
      redirect_to action: :index
    end

    private

    def find_course
      @course = Course.find params[:course_id]
    end
  end
end

app/views/admin/evaluaciones_formato/_formato.html.erb
<center>
  <table class="formato_evaluaciones">
    <tr>
      <th rowspan="2">Evaluación</th>
      <th colspan="4">
        Written
        (<%= @course.evaluacion_formato.term[:written] %> puntos)
      </th>
      <th colspan="2">
        Oral
        (<%= @course.evaluacion_formato.term[:oral] %> puntos)
      </th>
    </tr>
    <tr>
      <% Seccion.kinds.each do |kind| %>
        <th><%= kind %></th>
      <% end %>
    </tr>
    <% 1.upto(3).each do |i| %>
      <% if @course.evaluacion_formato.should_render?(i) %>
        <tr>
          <td><%= i %></td>
          <td>
            <%= formato_evaluacion_results_for i, "grammar" %>
          </td>
          <td>
            <%= formato_evaluacion_results_for i, "vocabulary" %>
          </td>
          <td>
            <%= formato_evaluacion_results_for i, "reading" %>
          </td>
          <td>
            <%= formato_evaluacion_results_for i, "writing" %>
          </td>
          <td>
            <%= formato_evaluacion_results_for i, "speaking" %>
          </td>
          <td>
            <%= formato_evaluacion_results_for i, "listening" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</center>

app/views/admin/evaluaciones_formato/index.html.erb
<div class="align_center">
  <h2>
    Formato de evaluaciones para <%= @course.nombre %>
  </h2>

  <div>
    <% if @course.evaluacion_formato %>
      <%= render "formato" %>
      <div class="actions">
        <%= link_to "Editar", edit_admin_course_evaluaciones_formato_path(@course, @course.evaluacion_formato), :class => "editar_edit" %>
        <%= link_to "Eliminar", admin_course_evaluaciones_formato_path(@course, @course.evaluacion_formato), method: :delete, :class => "delete_destroy" %>
      </div>
    <% else %>
      En este curso se pueden crear evaluaciones libremente
      <div>
        <%= link_to "Agregar formato de evaluaciones", new_admin_course_evaluaciones_formato_path(@course), :class => "crear_nuevo" %>
      </div>
    <% end %>
  </div>
</div>

<%= link_to "Cancelar", admin_courses_path, :class => "atras_back" %>

app/views/admin/evaluaciones_formato/new.html.erb
<div class="align_center">
  <h2>Formato de evaluaciones para <%= @course.nombre %></h2>
</div>

<div>
  <%= form_tag admin_course_evaluaciones_formato_index_path do %>

    <div class="field"></div>
    <div class="field evaluacion-formatos-count-js">
      <%= label_tag :formatos_count, "Número de evaluaciones" %>
      <%= select_tag :formatos_count, options_for_select([3], @formato.try(:formatos_count) || 3) %>
    </div>
    <div class="field"></div>

    <% 1.upto(1).each do |t| %>
      <!-- <h3>Term <%= t %></h3> -->
      <div class="margin_left has_separator">
        <table class="formato_evaluaciones">
          <tr>
            <th rowspan="2">Evaluación</th>
            <th colspan="4">
              Written
              <div class="input-append">
                <%= text_field_tag "terms[#{t}][written]", (@formato.points_for_section("written") if @formato) %>
                <span class="add-on">puntos</span>
              </div>
            </th>
            <th colspan="2">
              Oral
              <div class="input-append">
                <%= text_field_tag "terms[#{t}][oral]", (@formato.points_for_section("oral") if @formato) %>
                <span class="add-on">puntos</span>
              </div>
            </th>
          </tr>
          <tr>
            <th>Grammar</th>
            <th>Vocabulary</th>
            <th>Reading</th>
            <th>Writing</th>
            <th>Speaking</th>
            <th>Listening</th>
          </tr>
          <% 1.upto(3).each do |i| %>
            <tr class='evaluacion-row <%= "evaluacion-row-#{i}" %>'>
              <td><%= i %></td>
              <td>
                <%= formato_evaluacion_inputs_for t, i, "grammar" %>
              </td>
              <td>
                <%= formato_evaluacion_inputs_for t, i, "vocabulary" %>
              </td>
              <td>
                <%= formato_evaluacion_inputs_for t, i, "reading" %>
              </td>
              <td>
                <%= formato_evaluacion_inputs_for t, i, "writing" %>
              </td>
              <td>
                <%= formato_evaluacion_inputs_for t, i, "speaking" %>
              </td>
              <td>
                <%= formato_evaluacion_inputs_for t, i, "listening" %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    <% end %>

    <div class="actions">
      <%= link_to "Atrás", admin_course_evaluaciones_formato_index_path(@course), :class => "atras_back" %>
      <%= submit_tag "Enviar", data: {disable_with: "Enviando.."} %>
    </div>
  <% end %>
</div>